"use client";

import { CompleteReportData } from "@/lib/types";

interface CompleteReportProps {
  report: CompleteReportData | null;
  onClose: () => void;
}

export default function CompleteReport({ report, onClose }: CompleteReportProps) {
  if (!report) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="bg-[var(--bg-secondary)] border border-[var(--border-medium)] rounded-3xl w-full max-w-3xl max-h-[85vh] overflow-hidden flex flex-col shadow-2xl shadow-black/50">
        {/* Header */}
        <div className="px-7 py-5 border-b border-[var(--border-subtle)] flex items-center justify-between">
          <div>
            <h2 className="text-xl font-display text-white">Clinical Report</h2>
            <p className="text-[11px] text-[var(--text-muted)] uppercase tracking-wider mt-0.5">Generated by Nura Agent</p>
          </div>
          <button
            onClick={onClose}
            className="w-9 h-9 rounded-xl bg-[var(--bg-surface)] border border-[var(--border-subtle)] flex items-center justify-center text-[var(--text-muted)] hover:text-white hover:border-[var(--border-medium)] transition-all"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-7 space-y-7 scrollbar-thin">
          {/* Time Saved */}
          <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-cyan-500/10 via-blue-500/5 to-purple-500/10 border border-cyan-500/15 p-6 text-center">
            <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cdefs%3E%3Cpattern%20id%3D%22grid%22%20width%3D%2220%22%20height%3D%2220%22%20patternUnits%3D%22userSpaceOnUse%22%3E%3Cpath%20d%3D%22M%2020%200%20L%200%200%200%2020%22%20fill%3D%22none%22%20stroke%3D%22rgba(34%2C211%2C238%2C0.03)%22%20stroke-width%3D%221%22%2F%3E%3C%2Fpattern%3E%3C%2Fdefs%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22url(%23grid)%22%2F%3E%3C%2Fsvg%3E')] opacity-50" />
            <p className="text-[10px] font-bold text-cyan-300/70 uppercase tracking-[0.2em] mb-2 relative">Time Saved This Encounter</p>
            <p className="text-4xl font-display text-white relative">{report.time_saved}</p>
            <p className="text-[11px] text-[var(--text-muted)] mt-2 relative">
              Manual charting & documentation → Nura: Automated in real-time
            </p>
          </div>

          {/* SOAP Note */}
          <div>
            <h3 className="text-xs font-bold text-[var(--text-secondary)] uppercase tracking-[0.15em] mb-4 flex items-center gap-2">
              <span className="w-5 h-5 rounded-md bg-cyan-500/10 flex items-center justify-center text-[10px]">📋</span>
              SOAP Note
            </h3>
            <div className="space-y-4">
              <SOAPSection label="Subjective" content={report.soap_note.subjective} color="blue" />
              <SOAPSection label="Objective" content={report.soap_note.objective} color="emerald" />
              <SOAPSection label="Assessment" content={report.soap_note.assessment} color="purple" />
              <SOAPSection label="Plan" content={report.soap_note.plan} color="amber" />
            </div>
          </div>

          {/* Actions Summary */}
          <div>
            <h3 className="text-xs font-bold text-[var(--text-secondary)] uppercase tracking-[0.15em] mb-4 flex items-center gap-2">
              <span className="w-5 h-5 rounded-md bg-emerald-500/10 flex items-center justify-center text-[10px]">⚡</span>
              Autonomous Actions ({report.total_actions})
            </h3>
            <div className="space-y-2">
              {report.actions.map((action) => (
                <div
                  key={action.id}
                  className="flex items-center gap-3 text-xs bg-[var(--bg-primary)] rounded-xl p-3 border border-[var(--border-subtle)]"
                >
                  <span className="text-[10px] text-[var(--text-muted)] font-mono w-10 flex-shrink-0">
                    {formatTimestamp(action.timestamp)}
                  </span>
                  <span className={`px-2 py-0.5 rounded-md text-[9px] font-bold uppercase tracking-wider flex-shrink-0 ${
                    action.type === "alert"
                      ? "bg-rose-500/15 text-rose-300 border border-rose-500/15"
                      : action.type === "medication"
                      ? "bg-cyan-500/15 text-cyan-300 border border-cyan-500/15"
                      : action.type === "referral"
                      ? "bg-emerald-500/15 text-emerald-300 border border-emerald-500/15"
                      : "bg-slate-500/15 text-slate-300 border border-slate-500/15"
                  }`}>
                    {action.type}
                  </span>
                  <span className="text-[var(--text-secondary)] flex-1 truncate">
                    {getActionDescription(action)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-7 py-4 border-t border-[var(--border-subtle)] flex items-center justify-between">
          <p className="text-[10px] text-[var(--text-muted)]">
            Report generated autonomously by Nura AI Agent
          </p>
          <button
            onClick={onClose}
            className="px-5 py-2.5 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white text-sm font-semibold rounded-xl transition-all shadow-lg shadow-cyan-500/15"
          >
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
}

function SOAPSection({ label, content, color }: { label: string; content: string; color: string }) {
  const colorMap: Record<string, { border: string; label: string }> = {
    blue: { border: "border-blue-500/30", label: "text-blue-400" },
    emerald: { border: "border-emerald-500/30", label: "text-emerald-400" },
    purple: { border: "border-purple-500/30", label: "text-purple-400" },
    amber: { border: "border-amber-500/30", label: "text-amber-400" },
  };
  const c = colorMap[color] || colorMap.blue;

  return (
    <div className={`border-l-2 ${c.border} pl-4 py-1`}>
      <p className={`text-[10px] font-bold uppercase tracking-[0.15em] mb-1.5 ${c.label}`}>{label}</p>
      <p className="text-[13px] text-[var(--text-secondary)] leading-relaxed">{content}</p>
    </div>
  );
}

function formatTimestamp(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function getActionDescription(action: { type: string; content: Record<string, unknown> }): string {
  const content = action.content as Record<string, string>;
  switch (action.type) {
    case "alert": return content.description || "Clinical alert triggered";
    case "medication": return `Detected: ${content.name}${content.dosage ? ` (${content.dosage})` : ""}`;
    case "symptom": return content.description || "Symptom identified";
    case "condition": return `${content.name} (${content.status})`;
    case "referral": return `→ ${content.department}: ${content.reason}`;
    default: return JSON.stringify(content);
  }
}
