"use client";

import { useEffect, useRef } from "react";
import { CompleteReportData } from "@/lib/types";

interface CompleteReportProps {
  report: CompleteReportData | null;
  onClose: () => void;
}

export default function CompleteReport({ report, onClose }: CompleteReportProps) {
  const dialogRef = useRef<HTMLDivElement>(null);
  const previousFocusRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!report) return;
    previousFocusRef.current = document.activeElement as HTMLElement;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose();
        return;
      }
      if (e.key === "Tab" && dialogRef.current) {
        const focusable = dialogRef.current.querySelectorAll<HTMLElement>(
          'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
        );
        const first = focusable[0];
        const last = focusable[focusable.length - 1];
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault();
          last?.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first?.focus();
        }
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    // Focus the dialog
    setTimeout(() => {
      const firstBtn = dialogRef.current?.querySelector<HTMLElement>("button");
      firstBtn?.focus();
    }, 50);

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      previousFocusRef.current?.focus();
    };
  }, [report, onClose]);

  if (!report) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50" role="dialog" aria-modal="true" aria-labelledby="report-title" ref={dialogRef}>
      <div className="bg-white border border-[var(--border-subtle)] rounded-2xl w-full max-w-3xl max-h-[85vh] overflow-hidden flex flex-col shadow-2xl">
        {/* Header */}
        <div className="px-7 py-5 border-b border-[var(--border-subtle)] flex items-center justify-between bg-slate-50">
          <div>
            <h2 id="report-title" className="text-xl font-display font-bold text-[var(--text-primary)]">Clinical Report</h2>
            <p className="text-xs text-[var(--text-muted)] mt-0.5">Generated by Nura Agent</p>
          </div>
          <button
            onClick={onClose}
            aria-label="Close report"
            className="w-9 h-9 rounded-lg bg-white border border-[var(--border-subtle)] flex items-center justify-center text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:border-[var(--border-medium)] transition-all"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2} aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-7 space-y-7 scrollbar-thin">
          {/* Time Saved */}
          <div className="rounded-xl bg-blue-50 border border-blue-200 p-6 text-center">
            <p className="text-xs font-bold text-blue-600 uppercase tracking-wide mb-2">Time Saved This Encounter</p>
            <p className="text-4xl font-display font-bold text-blue-900">{report.time_saved}</p>
            <p className="text-sm text-blue-600 mt-2">
              Manual charting & documentation → Nura: Automated in real-time
            </p>
          </div>

          {/* SOAP Note */}
          <div>
            <h3 className="text-sm font-bold text-[var(--text-primary)] uppercase tracking-wide mb-4 flex items-center gap-2">
              <svg className="w-4 h-4 text-blue-700" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
              </svg>
              SOAP Note
            </h3>
            <div className="space-y-4">
              <SOAPSection label="Subjective" content={report.soap_note.subjective} color="blue" />
              <SOAPSection label="Objective" content={report.soap_note.objective} color="emerald" />
              <SOAPSection label="Assessment" content={report.soap_note.assessment} color="purple" />
              <SOAPSection label="Plan" content={report.soap_note.plan} color="amber" />
            </div>
          </div>

          {/* Actions Summary */}
          <div>
            <h3 className="text-sm font-bold text-[var(--text-primary)] uppercase tracking-wide mb-4 flex items-center gap-2">
              <svg className="w-4 h-4 text-blue-700" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
              </svg>
              Autonomous Actions ({report.total_actions})
            </h3>
            <div className="space-y-2">
              {report.actions.map((action) => (
                <div
                  key={action.id}
                  className="flex items-center gap-3 text-sm bg-slate-50 rounded-lg p-3 border border-[var(--border-subtle)]"
                >
                  <span className="text-xs text-[var(--text-muted)] font-mono w-10 flex-shrink-0">
                    {formatTimestamp(action.timestamp)}
                  </span>
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wide flex-shrink-0 ${
                    action.type === "alert"
                      ? "bg-red-100 text-red-700"
                      : action.type === "medication"
                      ? "bg-blue-100 text-blue-700"
                      : action.type === "referral"
                      ? "bg-emerald-100 text-emerald-700"
                      : "bg-slate-100 text-slate-600"
                  }`}>
                    {action.type}
                  </span>
                  <span className="text-[var(--text-secondary)] flex-1 truncate">
                    {getActionDescription(action)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-7 py-4 border-t border-[var(--border-subtle)] flex items-center justify-between bg-slate-50">
          <p className="text-xs text-[var(--text-muted)]">
            Report generated autonomously by Nura AI Agent
          </p>
          <button
            onClick={onClose}
            className="px-5 py-2.5 bg-blue-700 hover:bg-blue-800 text-white text-sm font-semibold rounded-lg transition-all"
          >
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
}

function SOAPSection({ label, content, color }: { label: string; content: string; color: string }) {
  const colorMap: Record<string, { border: string; label: string }> = {
    blue: { border: "border-blue-300", label: "text-blue-700" },
    emerald: { border: "border-emerald-300", label: "text-emerald-700" },
    purple: { border: "border-purple-300", label: "text-purple-700" },
    amber: { border: "border-amber-300", label: "text-amber-700" },
  };
  const c = colorMap[color] || colorMap.blue;

  return (
    <div className={`border-l-3 ${c.border} pl-4 py-1`} style={{ borderLeftWidth: '3px' }}>
      <p className={`text-xs font-bold uppercase tracking-wide mb-1.5 ${c.label}`}>{label}</p>
      <p className="text-sm text-[var(--text-secondary)] leading-relaxed">{content}</p>
    </div>
  );
}

function formatTimestamp(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function getActionDescription(action: { type: string; content: Record<string, unknown> }): string {
  const content = action.content as Record<string, string>;
  switch (action.type) {
    case "alert": return content.description || "Clinical alert triggered";
    case "medication": return `Detected: ${content.name}${content.dosage ? ` (${content.dosage})` : ""}`;
    case "symptom": return content.description || "Symptom identified";
    case "condition": return `${content.name} (${content.status})`;
    case "referral": return `→ ${content.department}: ${content.reason}`;
    default: return JSON.stringify(content);
  }
}
