"use client";

import { CompleteReportData } from "@/lib/types";

interface CompleteReportProps {
  report: CompleteReportData | null;
  onClose: () => void;
}

export default function CompleteReport({ report, onClose }: CompleteReportProps) {
  if (!report) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
      <div className="bg-[#12121a] border border-[#1e1e2e] rounded-2xl w-full max-w-3xl max-h-[85vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-[#1e1e2e] flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold text-white">Complete Clinical Report</h2>
            <p className="text-xs text-gray-400">Generated by WardScribe Agent</p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-[#0a0a0f] border border-[#2e2e3e] flex items-center justify-center text-gray-400 hover:text-white transition-colors"
          >
            ✕
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 scrollbar-thin">
          {/* Time Saved Metric */}
          <div className="bg-gradient-to-r from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 rounded-xl p-4 text-center">
            <p className="text-xs text-indigo-300 uppercase tracking-wider mb-1">Time Saved This Encounter</p>
            <p className="text-3xl font-bold text-white">{report.time_saved}</p>
            <p className="text-xs text-gray-400 mt-1">
              Traditional documentation: ~12 min → WardScribe: Real-time (0 additional min)
            </p>
          </div>

          {/* SOAP Note */}
          <div>
            <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
              <span className="w-6 h-6 rounded bg-indigo-500/20 flex items-center justify-center text-xs">📋</span>
              SOAP Note
            </h3>
            <div className="space-y-3">
              <SOAPSection
                label="Subjective"
                content={report.soap_note.subjective}
                color="blue"
              />
              <SOAPSection
                label="Objective"
                content={report.soap_note.objective}
                color="green"
              />
              <SOAPSection
                label="Assessment"
                content={report.soap_note.assessment}
                color="purple"
              />
              <SOAPSection
                label="Plan"
                content={report.soap_note.plan}
                color="amber"
              />
            </div>
          </div>

          {/* Actions Summary */}
          <div>
            <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
              <span className="w-6 h-6 rounded bg-green-500/20 flex items-center justify-center text-xs">⚡</span>
              Autonomous Actions Taken ({report.total_actions})
            </h3>
            <div className="space-y-2">
              {report.actions.map((action) => (
                <div
                  key={action.id}
                  className="flex items-center gap-3 text-xs bg-[#0a0a0f] rounded-lg p-2"
                >
                  <span className="text-gray-500 w-10">
                    {formatTimestamp(action.timestamp)}
                  </span>
                  <span
                    className={`px-2 py-0.5 rounded font-medium ${
                      action.type === "alert"
                        ? "bg-red-500/20 text-red-300"
                        : action.type === "medication"
                        ? "bg-blue-500/20 text-blue-300"
                        : action.type === "referral"
                        ? "bg-green-500/20 text-green-300"
                        : "bg-gray-500/20 text-gray-300"
                    }`}
                  >
                    {action.type}
                  </span>
                  <span className="text-gray-300 flex-1">
                    {getActionDescription(action)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-[#1e1e2e] flex items-center justify-between">
          <p className="text-xs text-gray-500">
            Report generated automatically by WardScribe AI Agent
          </p>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm rounded-lg transition-colors"
          >
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
}

function SOAPSection({
  label,
  content,
  color,
}: {
  label: string;
  content: string;
  color: string;
}) {
  const colorMap: Record<string, string> = {
    blue: "border-blue-500/30 text-blue-400",
    green: "border-green-500/30 text-green-400",
    purple: "border-purple-500/30 text-purple-400",
    amber: "border-amber-500/30 text-amber-400",
  };

  return (
    <div className={`border-l-2 ${colorMap[color]?.split(" ")[0]} pl-3`}>
      <p className={`text-xs font-semibold mb-1 ${colorMap[color]?.split(" ")[1]}`}>
        {label}
      </p>
      <p className="text-sm text-gray-300">{content}</p>
    </div>
  );
}

function formatTimestamp(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function getActionDescription(action: { type: string; content: Record<string, unknown> }): string {
  const content = action.content as Record<string, string>;
  switch (action.type) {
    case "alert":
      return content.description || "Clinical alert triggered";
    case "medication":
      return `Detected: ${content.name}${content.dosage ? ` (${content.dosage})` : ""}`;
    case "symptom":
      return content.description || "Symptom identified";
    case "condition":
      return `${content.name} (${content.status})`;
    case "referral":
      return `→ ${content.department}: ${content.reason}`;
    default:
      return JSON.stringify(content);
  }
}
